import Head from 'next/head';
import Image from 'next/image';

import { Card } from '@/components/Card';

export default function Home() {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-1 flex-col items-center justify-center py-16">
        <h1 className="m-0 text-center text-[4rem] leading-[1.15]">
          Welcome to{' '}
          <a
            className="text-[#0070f3] no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 text-center text-2xl leading-6">
          Get started by editing{' '}
          <code className="rounded-[5px] bg-slate-200 p-3 font-mono text-[1.1rem]">
            pages/index.js
          </code>
        </p>

        <div className="flex w-full max-w-[800px] flex-col flex-wrap items-center justify-center md:flex-row">
          <Card
            description="Find in-depth information about Next.js features and API."
            title="Documentation &rarr;"
            link="https://nextjs.org/docs"
          />
          <Card
            description="Learn about Next.js in an interactive course with quizzes!"
            title="Learn &rarr;"
            link="https://nextjs.org/learn"
          />
          <Card
            description="Discover and deploy boilerplate example Next.js projects."
            title="Examples &rarr;"
            link="https://github.com/vercel/next.js/tree/canary/examples"
          />
          <Card
            description="Instantly deploy your Next.js site to a public URL with Vercel."
            title="Deploy &rarr;"
            link="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          />
        </div>
      </main>

      <footer className="flex flex-1 items-center justify-center border-t border-t-[#eaeaea] py-8">
        <a
          className="flex flex-grow items-center justify-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="ml-2 h-4">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
